FROM php:7.3.6-fpm-alpine3.9
RUN apk add --no-cache openssl bash mysql-client
RUN docker-php-ext-install pdo pdo_mysql

# antes de rodar o docker-compose up -d
# no terminal dar permissão para a pasta storage
# chmod -R 755 storage

WORKDIR /var/www
RUN rm -rf /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN ln -s public html
RUN chown -R www-data:www-data /var/www

EXPOSE 9000
ENTRYPOINT ["php-fpm"]
